### ISSUE TITLE
PR could not be merged: API error in PUT to merge -- 'Resource not accessible by integration'

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/automerge-action#26]
Recently got the following error message from [the GHA automerge run]( https://github.com/conda-forge/nvcc-feedstock/actions/runs/3596801313/jobs/6057999837 ) when run on PR ( https://github.com/conda-forge/nvcc-feedstock/pull/94 ):

```python
ERROR:conda_forge_automerge_action.automerge:API error in PUT to merge
Traceback (most recent call last):
  File "/cf-autotick-bot-action/conda_forge_automerge_action/automerge.py", line 463, in _automerge_pr
    merge_status = pr.merge(
                   ^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/github/PullRequest.py", line 883, in merge
    headers, data = self._requester.requestJsonAndCheck(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
           ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/pulls#merge-a-pull-request"}
INFO:conda_forge_automerge_action.automerge:DID NOT MERGE PR 94 on conda-forge/nvcc-feedstock: PR could not be merged: API error in PUT to merge -- 'Resource not accessible by integration'
```

Note: This happened after restarting the action

**Comment by jakirkham** [comment]
Saw this [SO question]( https://stackoverflow.com/q/70435286 ) that might be related

**Comment by beckermr** [comment]
automerge has worked for me all afternoon so I hope this is a one-time thing. 

if you can leave the PR open next time, it will be easier to debug.

**Comment by jakirkham** [comment]
Ah apologies. Can do next time. Unfortunately was under some time pressure with this particular PR

**Comment by beckermr** [comment]
This has not come back, so I am closing for now. If we see it again, let's reopen.
